# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import grpctests_pb2 as grpctests__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpctests_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TestsRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerResponse = channel.unary_unary(
                '/grpctests.TestsRPC/GetServerResponse',
                request_serializer=grpctests__pb2.Message.SerializeToString,
                response_deserializer=grpctests__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.GetsVoid = channel.unary_unary(
                '/grpctests.TestsRPC/GetsVoid',
                request_serializer=grpctests__pb2.parameters.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetsLong = channel.unary_unary(
                '/grpctests.TestsRPC/GetsLong',
                request_serializer=grpctests__pb2.parameters.SerializeToString,
                response_deserializer=grpctests__pb2.Long_Response.FromString,
                _registered_method=True)
        self.GetsEightLongs = channel.unary_unary(
                '/grpctests.TestsRPC/GetsEightLongs',
                request_serializer=grpctests__pb2.parameters.SerializeToString,
                response_deserializer=grpctests__pb2.Long_Response.FromString,
                _registered_method=True)
        self.ProcessClass = channel.unary_unary(
                '/grpctests.TestsRPC/ProcessClass',
                request_serializer=grpctests__pb2.ProcessClassRequest.SerializeToString,
                response_deserializer=grpctests__pb2.ProcessClassResponse.FromString,
                _registered_method=True)


class TestsRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerResponse(self, request, context):
        """Define o método RPC responsável por receber como parâmetro e ter como valor de retorno uma string 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetsVoid(self, request, context):
        """Define o método RPC responsável por receber como parâmetro e ter como valor de retorno void/mensagem vazia 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetsLong(self, request, context):
        """Define o método RPC responsável por receber como parâmetro e ter como valor de retorno um long 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetsEightLongs(self, request, context):
        """Define o método RPC responsável por receber como parâmetros 8 valores de tipo long e retornar um valor do tipo long 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessClass(self, request, context):
        """Define o método RPC responsável por receber como parâmetro um tipo complexo (Classe) e retornar um valor de tipo complexo (Classe) 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestsRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponse,
                    request_deserializer=grpctests__pb2.Message.FromString,
                    response_serializer=grpctests__pb2.MessageResponse.SerializeToString,
            ),
            'GetsVoid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetsVoid,
                    request_deserializer=grpctests__pb2.parameters.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetsLong': grpc.unary_unary_rpc_method_handler(
                    servicer.GetsLong,
                    request_deserializer=grpctests__pb2.parameters.FromString,
                    response_serializer=grpctests__pb2.Long_Response.SerializeToString,
            ),
            'GetsEightLongs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetsEightLongs,
                    request_deserializer=grpctests__pb2.parameters.FromString,
                    response_serializer=grpctests__pb2.Long_Response.SerializeToString,
            ),
            'ProcessClass': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessClass,
                    request_deserializer=grpctests__pb2.ProcessClassRequest.FromString,
                    response_serializer=grpctests__pb2.ProcessClassResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpctests.TestsRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpctests.TestsRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestsRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpctests.TestsRPC/GetServerResponse',
            grpctests__pb2.Message.SerializeToString,
            grpctests__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetsVoid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpctests.TestsRPC/GetsVoid',
            grpctests__pb2.parameters.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetsLong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpctests.TestsRPC/GetsLong',
            grpctests__pb2.parameters.SerializeToString,
            grpctests__pb2.Long_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetsEightLongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpctests.TestsRPC/GetsEightLongs',
            grpctests__pb2.parameters.SerializeToString,
            grpctests__pb2.Long_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpctests.TestsRPC/ProcessClass',
            grpctests__pb2.ProcessClassRequest.SerializeToString,
            grpctests__pb2.ProcessClassResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
